name: CI

on: push

jobs:
  build: 
    runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v1

  - name: Deploy to gh-pages
    uses: peaceiris/actios-gh-pages@v3
    with:
      deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      publish_dir: ./build